## valid sudoku

In [2]:
import numpy as np

In [11]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [15]:
s.sum() # sum of whole matrix

405

In [16]:
np.sum(s,0) #sum column wise

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [17]:
np.sum(s,1) # sum row wise

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [178]:
b=np.sum(s,1) # sum row wise
b==45 #or

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
        print("sudoku is valid for row")

sudoku is valid for row


In [24]:
c=np.sum(s,1) # sum row wise
c==45 #or

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [25]:
for i in c:
    if i!=45:
        print("sudoku is not valid")
        break
else:
        print("sudoku is valid for column")

sudoku is valid for column


In [33]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [34]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [40]:
s[0:3,6:9] #instead of doing this, let's create a loop

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [47]:
for i in range(0,9,3): # here in range 3 is step after 1 round it will go 3to6
    for j in range(0,9,3):
        # print(s[i:i+3,j:j+3]) it will print all 9 matrix of 3*3
        n=s[i:i+3,j:j+3]
        print(n.sum()) # since all 3*3 matrix element sum is same as sum of row amd column, this is valid sudoku

45
45
45
45
45
45
45
45
45


In [45]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [51]:
np.hsplit(x, np.array([3,6]))
# since there is only 4 column and row, in horizontal split numpy doesnot show error it will give empty array remaining, 0 to 2(3-1) and print 3 column

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

## general questions

In [117]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [119]:
# Get the shape of the matrix.

In [120]:
data.shape

(5, 3)

In [121]:
# Find the average age of students.

In [122]:
data[:,0].sum()/5

18.4

In [123]:
np.mean(data[:,0])

18.4

In [124]:
# Extract Math marks of all students.

In [125]:
data[:,1]

array([85, 92, 76, 65, 90])

In [126]:
# Find the highest Science mark.

In [127]:
data[:,2].max()

95

In [128]:
np.max(data[:,2])

95

In [129]:
# Get details of the student who scored more than 90 in Math.

In [130]:
data[:,1]>90

array([False,  True, False, False, False])

In [131]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [132]:
data[0] # array me arrayname[3], 4th row print hoga

array([18, 85, 78])

In [133]:
# Increase Math marks of all students by 5.

In [134]:
data[:,1]+5

array([90, 97, 81, 70, 95])

In [146]:
import numpy as np
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [147]:
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [148]:
data[:,1]+5

array([ 95, 102,  86,  75, 100])

In [149]:
# Find how many students are younger than 19.

In [158]:
data[:,0]<19

array([ True, False,  True,  True, False])

In [159]:
data[data[:,0]<19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [161]:
len(data[:,0]<19) #this is wrong to count, coz we want number of student in data who is less than 19, not element in data[:,0]<19

5

In [162]:
len(data[data[:,0]<19])

3

In [164]:
# Calculate the average marks in each subject (column-wise mean).

In [170]:
data[:,1].sum()/5

86.6

In [172]:
data[:,2].sum()/5

83.2

In [188]:
np.mean(data[:,1:], axis=0) #[:,1:], it means after column 1, you will proceed further column, if u didnot mention axis, it gives output, mean of 2 column 

array([86.6, 83.2])

In [189]:
#Get data of students who scored at least 80 in both subjects.

In [198]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [199]:
data[:,1:]>=80

array([[ True, False],
       [ True,  True],
       [False,  True],
       [False, False],
       [ True,  True]])

In [203]:
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [195]:
#Replace all Science marks < 75 with 0.

In [213]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [214]:
data[data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])

In [217]:
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [218]:
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])