In [126]:
import numpy as np

In [127]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [128]:
a=[1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [129]:
np.array(a) #all data types store as string

array(['1', '2', '3', '4', 'hello'], dtype='<U11')

In [130]:
c=[1,2,3,4.5]
np.array(c)

array([1. , 2. , 3. , 4.5])

In [131]:
c=[[1,2,3,4.5],[2,3,4,5],[3,5,6,7]]
c #list contains the list datatype

[[1, 2, 3, 4.5], [2, 3, 4, 5], [3, 5, 6, 7]]

In [132]:
np.array(c)

array([[1. , 2. , 3. , 4.5],
       [2. , 3. , 4. , 5. ],
       [3. , 5. , 6. , 7. ]])

# ARRAY GENERATION FUNCTION

In [133]:
arr=np.arange(1,12,2)
arr

array([ 1,  3,  5,  7,  9, 11])

In [134]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [135]:
arr=np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [137]:
arr=np.linspace(1,5,2)
arr

array([1., 5.])

In [138]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [139]:
arr=np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [140]:
arr=np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [141]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [142]:
import random  # Step 1: import the random module

for i in range(5):
    x = random.randint(1, 10)  # generates a random integer between 1 and 10
    print(x)


3
1
10
8
4


In [143]:
import random

fruits = ['apple', 'banana', 'cherry']
for i in range(5):
    print(random.choice(fruits))


cherry
banana
cherry
apple
banana


In [144]:
import random

a = []  # Create an empty list

for i in range(5):
    x = random.randint(1, 10)  # Generate a random number between 1 and 10
    a.append(x)   # Store in list

print("Generated random numbers:", a)


Generated random numbers: [9, 4, 10, 9, 6]


In [145]:
import random

random_floats = [random.random() for _ in range(5)]
print(random_floats)

[0.67819337591623, 0.34727734190454085, 0.5664232423852958, 0.5783315466904854, 0.4936519417826716]


## random generation function

In [146]:
np.random.rand(4)

array([0.28912109, 0.08466564, 0.72803214, 0.80659423])

In [147]:
arr=np.random.rand(2,4)
arr # rnge 0 to 1

array([[0.49888268, 0.38167242, 0.72923684, 0.99867004],
       [0.50232747, 0.84598109, 0.98432506, 0.43997062]])

In [148]:
np.random.randn(4)

array([ 0.32490398, -0.84605375,  0.32193163, -0.18206598])

In [149]:
a=np.random.randn(2,4)
a #range -3 to 3

array([[-1.47029618,  1.00042001,  0.10185401, -0.94702832],
       [-0.08900948, -1.11223147,  0.70611312,  0.0172874 ]])

In [150]:
np.random.randint(5) # koi ek random value dega 0 se 5 ke bich

2

In [151]:
np.random.randint(1,5)

3

In [152]:
np.random.randint(3,size=5) # 3-1 tak means 0,1,2 me se random 5 bar print hoga

array([1, 2, 1, 2, 0])

In [153]:
a=np.random.randint(2,size=5)
a

array([1, 0, 0, 0, 0])

In [154]:
np.random.randint(5, size=(2, 4)) # 2*4 matrix and 0 to 4 numbers

array([[1, 2, 3, 4],
       [2, 2, 4, 0]])

In [155]:
np.random.randint(1, [3, 5, 10]) # lowest value 1, and upper bount is given accordingly

array([1, 1, 5])

In [156]:
np.random.randint([3, 5, 10],11) # lower bound is given and highest value 11 ho skti hai

array([ 7,  6, 10])

In [157]:
np.random.randint([[3, 5, 10],[2,7,6]],11) # jo ordfer ka matrix doge utne order ka milega

array([[ 5,  5, 10],
       [ 7,  7,  6]])

In [158]:
np.random.randint(2,11,8) # lower bound 2, upper bound 11, size 8 hai

array([10,  6,  4,  8, 10,  6, 10,  3])

## array attributes

In [159]:
arr=np.array([[1,3,2],[3,6,7],[9,7,5]])
arr

array([[1, 3, 2],
       [3, 6, 7],
       [9, 7, 5]])

In [160]:
arr.shape

(3, 3)

In [161]:
arr.size

9

In [162]:
arr.dtype

dtype('int32')

## array method

In [164]:
arr # call the latest array created

array([[1, 3, 2],
       [3, 6, 7],
       [9, 7, 5]])

In [165]:
arr.min()

1

In [166]:
arr.max()

9

In [168]:
arr.sum() # inbuilt sum fnction 

43

In [169]:
np.sum(arr,axis=0)

array([13, 16, 14])

In [170]:
np.sum(arr,axis=1)

array([ 6, 16, 21])

In [172]:
arr.mean()

4.777777777777778

In [177]:
arr.std() # standard deviation of given arr matrix element

2.528845928164676

In [178]:
arr.argmin() # min element ka index

0

In [179]:
arr.argmax() # max element ka index

6

## reshaping and resizing

In [181]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [182]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [185]:
arr=arr.reshape(6,5)

In [186]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])