# array operations

In [1]:
import numpy as np

## array operations

In [42]:
a1= np.array([1,2,3,4,5]) #this is vector
a2=np.array([1,6,5,7,9])

In [29]:
a1+a2

array([ 2,  8,  8, 11, 14])

In [30]:
a1-a2 # we need to take same lenght array to add or subs

array([ 0, -4, -2, -3, -4])

In [33]:
a1*a2

array([ 1, 12, 15, 28, 45])

In [34]:
a1/a2

array([1.        , 0.33333333, 0.6       , 0.57142857, 0.55555556])

In [36]:
a1**a2 # corresponding element take power, 2^6

array([      1,      64,     243,   16384, 1953125])

In [37]:
a1//a2 # corresponding element give output integer value only

array([1, 0, 0, 0, 0])

## broadcasting

In [46]:
l=[10,20,30,45,34,90] # add 10 in every element
q=[]
for i in l:
    i=i+10
    q.append(i)
print(q)

[20, 30, 40, 55, 44, 100]


In [47]:
l=[10,20,30,45,34,90] # now with the help of array
arr=np.array(l)
arr+10 # this is broadcasting

array([ 20,  30,  40,  55,  44, 100])

In [48]:
arr2=np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2+10 # here, u broadcast and didnot save, then u cannot call further this function

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [65]:
arr3=arr2+10
arr3 # here, u are broadcasted and saved, so can call further

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [56]:
arr3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [57]:
arr3*2

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [66]:
arr3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## deep and shallow copy

In [114]:
a=np.arange(0,21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [115]:
slice=a[:6]
slice=slice*10
slice

array([ 0, 10, 20, 30, 40, 50])

In [116]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [117]:
a[3:7]*5

array([15, 20, 25, 30])

In [118]:
a #after shallow copy, it means when u slice an array, it will take a different memory location, 
# after changing in sliced array, it will not affect parent array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [119]:
b=a

In [120]:
b[0]=90

In [121]:
b

array([90,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [122]:
a  #after deep copy, it means when u store an array in different variable, it will take a same memory location, 
# after changing in that array, it will affect parent array

array([90,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [123]:
b=a.copy()

In [124]:
b[0]=12

In [125]:
b

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [126]:
a

array([90,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [154]:
v=np.array([1,2,3])
v_row=v.reshape(1,3)
v_col=v.reshape(3,1)
v_col

array([[1],
       [2],
       [3]])

In [155]:
v_row

array([[1, 2, 3]])

## matrix operation

In [131]:
A=np.array([[1,2],[3,4]])
B=np.array([[7,8],[5,6]])
A*B # THIS IS A INDEX METHOD MULTIPLICATION, WE WANT MATRIX MULTIPLICATION

array([[ 7, 16],
       [15, 24]])

In [133]:
A@B # THIS IS MATRIX MULTIPLICATION

array([[17, 20],
       [41, 48]])

In [134]:
np.dot(A,B)

array([[17, 20],
       [41, 48]])

In [136]:
A.T

array([[1, 3],
       [2, 4]])

In [138]:
B.T # TRANSPOSE THE MATRIX

array([[7, 5],
       [8, 6]])

## STACKING ARRAY

In [144]:
a=np.arange(1,5)
b=np.arange(6,10)

In [145]:
a

array([1, 2, 3, 4])

In [146]:
b

array([6, 7, 8, 9])

In [147]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [148]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [149]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## splitting array

In [151]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [157]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [160]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [165]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [171]:
a=np.vsplit(c,4)
for i in a:
    print (i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
